gardener/gardenlogin

.github/workflows/update-gardenlogin.yaml
https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
> **Pin actions to a full length commit SHA**
> 
> Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
Fixes #
```feature user
```
=> Pin github actions

Makefile
This PR adds a help make target to print out all available targets with their short description
Also, the currently unused `generate` target was removed
Fixes #
```feature user
```
=> Add help make target

.github/workflows/update-gardenlogin.yaml
With this PR the gardenlogin darwin-arm64 release asset will be uploaded on the next release
Fixes #
```bugfix user
Fixed missing `gardenlogin_darwin_arm64` release asset upload
```
=> [hotfix-v0.1] Fix darwin-arm64 release asset upload

.github/workflows/update-gardenlogin.yaml
With this PR the gardenlogin darwin-arm64 release asset will be uploaded on the next release
Fixes #
```feature user
```
=> [master] Fix darwin-arm64 release asset upload

README.md, cmd/get_client_certificate.go, cmd/root.go, internal/certificatecache/store/store.go, internal/certificatecache/types.go, internal/cmd/util/config.go, internal/cmd/util/factory.go
1. ⚠️ the configuration properties have changed to align with `gardenctl-v2`. The following properties were marked deprecated. The local config file should be adapted accordingly:
- `gardenClusters` was renamed to `gardens`
- `clusterIdentity` was renamed to `identity`
2. If no configuration file is found (`~/.garden/gardenlogin.yaml`), it falls back to the `gardenctl-v2` configuration file (`~/.garden/gardenctl-v2.yaml`) which shares the same configuration properties.
Fixes #
```other user
⚠️ the configuration properties have changed to align with `gardenctl-v2`. Please rename your configuration properties accordingly as they may not be supported with future …
```
=> Configuration changes - Fallback to `gardenctl-v2` config and property name changes

cmd/get_client_certificate.go
Fixed an issue where instead of the user the context name was returned for a given cluster name. This resulted in the error message `Error: failed to get ExecCredential: could not find matching auth info from shoot kubeconfig for given cluster: no matching user config found for user name garden-myproject--mycluster-internal`.
This issue usually occurred when switching from the default `*-external` context (`garden-myproject--mycluster-external`) to the internal context (`garden-myproject--mycluster-internal`). 
The reason why it worked (by chance) for the default context is, that the user is named as the context (`garden-myproject--mycluster-external`). 
See example kubeconfig that is returned by the `shoots/adminkubeconfig` subresource
```yaml …
```
=> Use username instead of context name

README.md, cmd/get_client_certificate.go, cmd/root.go, internal/cmd/util/config.go, internal/cmd/util/factory.go
This PR allows to override the current context of the `garden` cluster `kubeconfig`.
Example:
```yaml
gardens:
- identity: landscape-dev # Unique identity of the garden cluster. See cluster-identity ConfigMap in kube-system namespace of the garden cluster
kubeconfig: ~/path/to/garden-cluster/kubeconfig.yaml
context: different-context # Overrides the current-context of the garden cluster kubeconfig  
```
Fixes #
```feature user
You can now override the current context of the `garden` cluster `kubeconfig` by setting the `gardens[].context` property in your `gardenlogin` config file.
```
=> Override current-context of garden cluster kubeconfig

cmd/get_client_certificate.go
When trying to find a matching cluster from the kubeconfig returned by the `shoots/adminkubeconfig` endpoint, the ca is not considered anymore. The additional check for a matching ca caused issues when rotating the clusters CA. The check is not necessarily needed, as it is assumed that the `shoots/adminkubeconfig` endpoint returns a cluster list with unique `cluster.server` fields.
Fixes #28 
```bugfix user
Fixed an issue where `gardenlogin` would report that no matching cluster could be found for server and certificate-authority-data in case the Shoot cluster CA is being rotated
```
=> Use only server to find matching cluster

.ci/pipeline_definitions, .github/workflows/update-gardenlogin.yaml, go.mod
Bumps golang from 1.18 to 1.19.5
Fixes #
```feature user
```
=> Bump golang from 1.18 to 1.19.5

.gimps.yaml, Makefile, README.md, cmd/cmd_suite_test.go, cmd/get_client_certificate.go, cmd/get_client_certificate_test.go, example/01-kubeconfig.yaml, hack/golangci-lint.sh, internal/clientauthentication/clientauthentication_suite_test.go, internal/clientauthentication/conversion.go, internal/clientauthentication/conversion_test.go, main.go
Fixed issue when exec plugin in kubeconfig is configured to use API version `client.authentication.k8s.io/v1`:
```
users:
- name: garden-core--peter-test
user:
exec:
apiVersion: client.authentication.k8s.io/v1
```
Previously the error `Error: failed to complete command options: cannot convert to ExecCredential: %!w(<nil>)` was returned.
With this PR `client.authentication.k8s.io/v1` is supported. Depending on the configured API version an `ExecCredential` with the same API version is returned. Currently supported versions:
- `client.authentication.k8s.io/v1`
- `client.authentication.k8s.io/v1beta1`
Fixes #
```feature user
`client.authentication.k8s.io/v1` is now …
```
=> Support v1 ExecCredential

.github/workflows/golangci-lint.yml, cmd/get_client_certificate.go, hack/golangci-lint.sh
Bumps golangci-lint to v1.52.2
Fixes #
```feature user
```
=> Bump golangci-lint to v1.52.2

internal/cmd/util/config.go
This PR removes the deprecated `gardenClusters` property. This property was deprecated since `v0.2.0`
Fixes #
```breaking user
The deprecated config properties (since `v0.2.0`, https://github.com/gardener/gardenlogin/pull/20) are not supported anymore. If not already done update your config file:
- `gardenClusters` was renamed to `gardens`
- `clusterIdentity` was renamed to `identity`
```
=> Remove deprecated config property

.ci/pipeline_definitions, .github/workflows/golangci-lint.yml, .github/workflows/update-gardenlogin.yaml, .golangci.yaml, go.mod
- Bump golang to `1.21.6`
- Bump golangci-lint action to `v1.55.2`
- Temporarily disable `dot-import` revive lint rule
Fixes #
```feature user
```
=> Bump golang to 1.21.6

README.md, cmd/get_client_certificate.go, cmd/get_client_certificate_test.go, internal/certificatecache/store/store_test.go, internal/certificatecache/types.go
Viewer credentials can now be requested using the flag `--access-level=viewer`
Fixes #
https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#shootsviewerkubeconfig-subresource
```feature user
`get-client-certificate`: Viewer credentials can now be requested using the flag `--access-level=viewer`
```
=> Support `shoots/viewerkubeconfig`

cmd/get_client_certificate.go
Previously, as `viewer` with `access-level` flag set to `auto`, every time a new credential is fetched a log entry is written, which would annoy the user. 
```bash
k get configmap
I0208 15:14:58.553441   10796 get_client_certificate.go:434] "No permission to obtain admin kubeconfig. Falling back to obtaining viewer kubeconfig." error="shoots.core.gardener.cloud \"myshoot\" is forbidden: User \"system:serviceaccount:garden-myproject:robot\" cannot create resource \"shoots/adminkubeconfig\" in API group \"core.gardener.cloud\" in the namespace \"garden-myproject\""
NAME               DATA   AGE
kube-root-ca.crt   1      7d4h
```
With this PR, you have to set `--v=4` or higher to see the fallback log entry.
Fixes # …
=> [hotfix-v0.5] Log `shoots/viewerkubeconfig` fallback with V-level `4`

cmd/get_client_certificate.go
Previously, as `viewer` with `access-level` flag set to `auto`, every time a new credential is fetched a log entry is written, which would annoy the user. 
```bash
k get configmap
I0208 15:14:58.553441   10796 get_client_certificate.go:434] "No permission to obtain admin kubeconfig. Falling back to obtaining viewer kubeconfig." error="shoots.core.gardener.cloud \"myshoot\" is forbidden: User \"system:serviceaccount:garden-myproject:robot\" cannot create resource \"shoots/adminkubeconfig\" in API group \"core.gardener.cloud\" in the namespace \"garden-myproject\""
NAME               DATA   AGE
kube-root-ca.crt   1      7d4h
```
With this PR, you have to set `--v=4` or higher to see the fallback log entry.
Fixes # …
=> [master] Log `shoots/viewerkubeconfig` fallback with V-level `4`

README.md
`sudo` is needed for symlink to create `/usr/local/bin/kubectl-gardenlogin`
Fixes #
```doc user
Fix for install doc on linux
```
=> prepended sudo to gardenlogin symlink

.ci/pipeline_definitions
Configure the europe-docker.pkg.dev/gardener-project/releases OCM repository as lookup, so that the head-update job (which only knows the .../snapshots repository by now), also detects the release version in .../releases repository
Fixes #
```feature user
```
=> Add ocm repository mappings

.ci/build, .ci/pipeline_definitions
To model the built gardenlogin binaries as delivery relevant artefacts, they should be part of the component descriptor's resources. Since the binaries are already configured as output of the build step, this output can be used to create additional release assets.
Fixes #
```feature user
```
=> Add binaries as release assets to component descriptor

.ci/pipeline_definitions
We should transition to reusing the binaries generated by the CI pipeline instead of building them separately in the Action (or vice versa, as described in https://github.com/gardener/gardenlogin/issues/182). Currently, we have disabled the binary upload from the CI pipeline, but this should be re-enabled once we implement the proper reuse strategy.
Fixes #
https://github.com/gardener/cc-utils/pull/1120
```feature user
```
=> chore: Disable binary upload

.github/workflows/reuse-tool-lint.yaml
Potential fix for [https://github.com/gardener/gardenlogin/security/code-scanning/1](https://github.com/gardener/gardenlogin/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the workflow level to explicitly define the required permissions. Since the workflow only performs a compliance check, it likely only needs `contents: read` permission. This will ensure the workflow adheres to the principle of least privilege and avoids unnecessary write access.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 1: Workflow does not contain permissions

.golangci.yaml
This PR fixes the following warning by using golangci-lint `wsl_v5`:
```bash
WARN The linter "wsl" is deprecated (since v2.2.0) due to: new major version. Replaced by wsl_v5.
WARN [linter] `allow-multiline-assign` is deprecated and always allowed in wsl >= v5
WARN Suggested new configuration:
linters:
enable:
- wsl_v5
settings:
wsl_v5:
allow-first-in-block: true
allow-whole-block: false
branch-max-lines: 2
```
Fixes #
```other operator
```
=> Use golangci-lint `wsl_v5`

.github/workflows/prepare-hotfix-branch.yaml
This PR adds a workflow to prepare hotfix a branch. The workflow will create a PR for applying the changes to the newly created hotfix branch. The workflow accepts the tag, for which a hotfix branch should be created.
The dashboard workflow is being reused ([ref](https://github.com/gardener/dashboard/pull/2578)).
Fixes #
```feature user
```
=> Add workflow to prepare hotfix branch

.github/workflows/cherry-pick.yaml
With this PR, the cherry-pick action(s) from the gardener/dashboard repository are reused. Only the cherry-pick workflow file needs to be duplicated
Fixes #
```feature user
```
=> GithubAction: Reuse cherry-pick action
