- .ci/build
- .github/workflows/update-gardenlogin.yaml
- Makefile
- hack/build-windows-amd64.sh
> Added windows build target

- .github/workflows/update-gardenlogin.yaml
> Use app token instead of pat

- .github/workflows/update-gardenlogin.yaml
> Add trigger for chocolatey repository

- README.md
> Update README.md - Add installation instructions

- Makefile
- hack/build-darwin-arm64.sh
- hack/get-build-ld-flags.sh
Added build for apple arm (silicon) processors
Fixes #
```feature user
```
> Added build for apple arm (silicon) processors

- .github/workflows/update-gardenlogin.yaml
> updated workflow actions

- .github/workflows/update-gardenlogin.yaml
> Do not trigger brew / choco actions for pre-releases

- README.md
There should be a reason why we have a version var (unused otherwise).
Fixes #
```feature user
```
> doc: Improve install from Github release

- .github/workflows/reuse-tool-lint.yaml
- .reuse/dep5
Adds reuse github action and fixes lint errors
Fixes #
```feature user
```
> add reuse github action and fix lint errors

- .github/workflows/golangci-lint.yml
- .golangci.yaml
- cmd/get_client_certificate.go
- cmd/get_client_certificate_test.go
- cmd/root.go
- cmd/version.go
- cmd/version_test.go
- hack/golangci-lint.sh
- internal/certificatecache/store/store.go
- internal/certificatecache/store/store_test.go
- internal/cmd/util/clock.go
- internal/cmd/util/config.go
- internal/cmd/util/factory.go
- Adds golangci-lint's github action
- Enables additional linters
- Fixes lint errors
Fixes #
```feature user
```
> Add golangci-lint's github action and enable additional linters

- .github/workflows/update-gardenlogin.yaml
This PR includes some necessary maintenance for the Github workflows.
- updated dependencies to latest versions
- replaced hard coded repository names
- upgraded deprecated set-output commands to using Environment Files
Fixes #
```feature user
```
> workflow maintenance

- cmd/get_client_certificate.go
- cmd/root.go
Migrate to structured and contextual logging
Fixes #
- [pitfalls-during-usage](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging#pitfalls-during-usage) 
- https://www.kubernetes.dev/blog/2022/05/25/contextual-logging/
```feature user
```
> Migrate to structured and contextual logging

- README.md
This PR makes it clearer for users where to store the config file. 
Fixes #
```feature user
```
> Add config file placement hint

- .github/workflows/update-gardenlogin.yaml
- Makefile
- hack/build-darwin-amd64.sh
- hack/build-darwin-arm64.sh
- hack/build-linux-arm64.sh
- hack/build-windows-amd64.sh
- hack/build.sh
Build binary for linux/arm64
Fixes #
```feature user
`gardenlogin` is now also available for linux/arm64
```
> Build binary for linux/arm64

- CONTRIBUTING.md
- LICENSE
- LICENSES/Apache-2.0.txt
- README.md
* Updated `CONTRIBUTING.md` file
* Updated `LICENSE` file
* Updated `LICENSES` folder
* Added badge for reuse compliance in `README.md` file and registered repo with REUSE API
> Make repo compliant

- .github/workflows/release.yaml
> Declare release assets

- README.md
> Add CI Build badge

- .github/workflows/build.yaml
Disable cache for release builds
Fixes #
```feature user
```
> disable cache for release builds

- .github/workflows/release.yaml
Do not bump `LATEST` version file when creating bump commit
Fixes #
```feature user
```
> Do not bump `LATEST` version file for bump commit

- .ci/build
- .ci/verify
- .github/workflows/build.yaml
- hack/build-darwin-amd64.sh
- hack/build-darwin-arm64.sh
- hack/build-linux-amd64.sh
- hack/build-linux-arm64.sh
- hack/build-windows-amd64.sh
- hack/build.sh
- hack/golangci-lint.sh
- hack/test-integration.sh
Replaces flexible additional flags in CI and hack scripts with explicit variables for timeout, race detection, and verbosity.
Fixes #
related PR https://github.com/gardener/terminal-controller-manager/pull/410
```feature user
```
> ci: replace additional flags with explicit vars
